=== atikrahman146/AdvanceJava/nov11_DomParser/domparser.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/domparser.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE st:class SYSTEM "domparser.dtd">

    <st:class>
    ...
    </st:class>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT st:class (st:student)*>
<!ATTLIST st:class
    xmlns:st CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT st:student (st:firstname|st:lastname|st:marks)*>
<!ATTLIST st:student
    rollno CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT st:firstname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT st:lastname (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT st:marks (#PCDATA)>

=== atikrahman146/AdvanceJava/nov11_DomParser/domparser.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE st:class SYSTEM "domparser.dtd">
<st:class xmlns:st="smd">
    <st:student rollno="1232383">
        <st:firstname>Atik</st:firstname>
        <st:lastname>Topper</st:lastname>
        <st:marks>100000</st:marks>
    </st:student>
    <st:student rollno="1232323">
        <st:firstname>Shahriar</st:firstname>
        <st:lastname>Topper</st:lastname>
        <st:marks>100000</st:marks>
    </st:student>
</st:class>
