=== atikrahman146/AdvanceJava/nov05_xml/StudentList.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/StudentList.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE studentlist SYSTEM "StudentList.dtd">

    <studentlist>
    ...
    </studentlist>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT studentlist (student)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT student (id|name|age|email)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT id (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT name (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT age (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT email (#PCDATA)>

<!ENTITY copyright "&copyright; 2001 Jon David &documentDate;">

=== atikrahman146/AdvanceJava/nov05_xml/StudentList.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE studentlist SYSTEM "StudentList.dtd">
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<studentlist>
    <student>
        <id>1232383</id>
        <name>Demo</name>
        <age>27</age>
        <email>demo@demo.com</email>
    </student>
    <student>
        <id>1232328</id>
        <name>Demo1</name>
        <age>28</age>
        <email>demo1@demo.com</email>
        copyright
    </student>
</studentlist>
